spring.application.name=Dukaan

# 1. Database Connection URL
# 'localhost' is your Mac, '3306' is the default MySQL port, 'shopping_cart_db' is your DB name
spring.datasource.url=jdbc:mysql://localhost:3306/shopping_cart_db

# 2. Database Credentials
spring.datasource.username=root
spring.datasource.password=########

# 3. Driver Class Name (Tells Spring how to talk to MySQL)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Useful Debugging (Shows the SQL queries in your VS Code terminal)
spring.jpa.show-sql=true
logging.level.org.springframework.jdbc.core=DEBUG